name       : convmv
version    : 2.0
release    : 1
source     :
    - https://www.j3e.de/linux/convmv/convmv-2.0.tar.gz : 170cf675be1fca77868ff472e9340ca828b1463865a63d4f4b7b3bf4053db93f
license    : GPL-2.0
component  : system.utils
summary    : converts filenames from one encoding to another
description: |
    converts filenames from one encoding to another
builddeps  :
    - gcc
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
